In [26]:
#import nececcasy libraries
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib as plt
import seaborn as sns

In [29]:
#price List
price_dict={'Coffee':2,'Tea':1.5,'Sandwich':4,'Salad':5,'Cake':3,'Cookie':1,'Smoothie':4,'Juice':3}

In [3]:
#import the csv file
df= pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\datasets projects\cafe_sales.csv")

### Initial Checks

In [4]:
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [30]:
#check duplicates(none present)
df.duplicated().sum()

0

In [31]:
#check null values in each column
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

### For Column- Item

In [32]:
#what all values are present
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'Sandwich',
       'Juice', 'Tea'], dtype=object)

In [33]:
#remove whitespaces if any
df['Item'] = df['Item'].str.strip().str.capitalize()

In [34]:
#replace irrelevant entries
df['Item']=df['Item'].replace(['Unknown','Error'],pd.NA)

In [11]:
#remove null values
df.dropna(subset=['Item'], inplace=True)

### For Column- Location

In [13]:
#what all values are present
df['Location'].unique()

array(['Takeaway', 'In-store', 'UNKNOWN', nan, 'ERROR'], dtype=object)

In [14]:
#fill null values
df['Location']=df['Location'].fillna('Delivery')

In [35]:
#replace irrelevant entries with Delivery
df['Location']=df['Location'].replace('UNKNOWN','Delivery')
df['Location']=df['Location'].replace('ERROR','Delivery')

### For Column- Quantity

In [37]:
#what all values are present
df['Quantity'].unique()

array([2., 4., 5., 3., 1.])

In [36]:
#convert to float values
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [38]:
#remove null values
df.dropna(subset=['Quantity'], inplace=True)

### For Column- Price per unit

In [39]:
#what all values are present
df['Price Per Unit'].unique()

array([2. , 3. , 1. , 5. , 4. , 1.5])

In [40]:
#turn to float values
df['Price Per Unit'] = pd.to_numeric(df['Price Per Unit'], errors='coerce')

In [41]:
#map the prices from the prices at the beginning
df['Price Per Unit'] = df['Price Per Unit'].fillna(df['Item'].map(price_dict))

### For Column- Total Spent

In [42]:
#turn to float values
df['Total Spent'] = pd.to_numeric(df['Total Spent'], errors='coerce')

In [43]:
#total=Price*quantity
df['Total Spent']=df['Quantity']*df['Price Per Unit']

### For Column- Payment Method

In [44]:
#what all values are present
df['Payment Method'].unique()

array(['Credit Card', 'Cash', 'UPI', 'Swiggy Dineout'], dtype=object)

In [45]:
#replace irrelevant entries with UPI, and replace Digital Wallet with Swiggy Dineout

df['Payment Method']=df['Payment Method'].replace(['UNKNOWN','ERROR'],pd.NA)
df['Payment Method']=df['Payment Method'].replace('Digital Wallet','Swiggy Dineout')
df['Payment Method']=df['Payment Method'].fillna('UPI')

### For Column- Transaction Date

In [24]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'], errors='coerce')

In [25]:
df = df.dropna(subset=['Transaction Date'])

### Final Checks

In [46]:
df.isnull().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [47]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,4.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UPI,Delivery,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Swiggy Dineout,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,2.0,4.0,8.0,Cash,Delivery,2023-10-20
9995,TXN_7672686,Coffee,2.0,2.0,4.0,UPI,Delivery,2023-08-30
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Swiggy Dineout,Delivery,2023-03-02
9998,TXN_7695629,Cookie,3.0,1.0,3.0,Swiggy Dineout,Delivery,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8215 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    8215 non-null   object
 1   Item              8215 non-null   object
 2   Quantity          8215 non-null   float64
 3   Price Per Unit    8215 non-null   float64
 4   Total Spent       8215 non-null   float64
 5   Payment Method    8215 non-null   object
 6   Location          8215 non-null   object
 7   Transaction Date  8215 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(3), object(4)
memory usage: 577.6+ KB